apiVersion: v1
kind: Pod
metadata:
  name: fapp
  labels:
    app: fapplabel
spec:
  containers:
  - name: fappc
    image: balanus/fapp:v1
    ports:
    - name:  containerport
      containerPort: 3000
      protocol: TCP
    resources:
      limits:
        memory: "100Mi"
        cpu: "100m"