apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bggapp-hpa
spec:
  maxReplicas: 100
  minReplicas: 1
  scaleTargetRef: 
    apiVersion: extensions/v1beta1
    name: bggapp
    kind: Deployment
  targetCPUUtilizationPercentage: 80
