apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: exapp-hpa
spec:
  maxReplicas: 7
  minReplicas: 1
  scaleTargetRef: 
    apiVersion: extensions/v1beta1
    name: exapp
    kind: Deployment
  targetCPUUtilizationPercentage: 3
